services:
  # Service Backend
  api:
    build:
      context: ./devops-tutor
      dockerfile: Dockerfile
    ports:
      - "3003:3000" 
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY} 
    networks:
      - app-network

  # Service Frontend
  web:
    build:
      context: ./frontend-tutor
      dockerfile: Dockerfile
    ports:
      - "8080:80" 
    depends_on:
      - api 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge